version: "3"

services:
  real_world_api:
    image: ghcr.io/afanasievkirill/real_world/real_world_api_example:develop
    container_name: real_world_api
    restart: unless-stopped
    command: [ 'npm run typeorm migration:run', 'npm run start' ]
    depends_on:
      - real_world_api_db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  db:
    image: postgres:13.1
    container_name: real_world_api_db
    hostname: real_world_api_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./pg_db:/var/lib/postgresql
      - ./pg_data:/var/lib/postgresql/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  pg_db:
    driver: local
  pg_data:
    driver: local
